release tag and adjust version

diff --git a/usr/share/rear/contrib/obs_package_download b/usr/share/rear/contrib/obs_package_download
--- a/usr/share/rear/contrib/obs_package_download
+++ b/usr/share/rear/contrib/obs_package_download
@@ -3,11 +3,10 @@
 # download all binaries from obs
 #
 # params:
-# $1 = rear version
-# $2 = destination dir
+# $1 = dest dir
 #
 # in the destination dir we build a directory structure like this:
-# <version>/<distro>/<arch>
+# <distro>/<arch>
 
 OBS_PROJECT=home:sschapiro
 OBS_PACKAGE=ReaR
@@ -17,15 +16,14 @@ die() {
 	exit 1
 }
 
-test "$1" -a "$2" -a -d "$2" || die "wrong args. Usage: $0 <version> <dest-dir>"
+test "$1" -a -d "$1" || die "wrong args. Usage: $0 <dest-dir>"
 
-DEST_DIR="$2/$1"
-
-mkdir -p "$DEST_DIR" || die "Could not mkdir $DEST_DIR"
+DEST_DIR="$1"
 
 while read REPO ARCH junk ; do
 	test "$REPO" -a "$ARCH" || die "could not read distro and arch: '$REPO $ARCH $junk'"
-	mkdir -p "$DEST_DIR/$REPO/$ARCH"
+	mkdir -p "$DEST_DIR/$REPO/$ARCH" || die "Could not mkdir '$DEST_DIR/$REPO/$ARCH'"
+	echo "Retrieving $REPO $ARCH:"
 	osc getbinaries -d "$DEST_DIR/$REPO/$ARCH" $OBS_PROJECT $OBS_PACKAGE $REPO $ARCH || die "Could not fetch binaries for $OBS_PROJECT $OBS_PACKAGE $REPO $ARCH"
 done < <(osc repos $OBS_PROJECT)
 
