- added -L to stat call to read real device in 29_find_required_devices.sh - make svn2host report scp errors

diff --git a/usr/share/rear/contrib/svn2host b/usr/share/rear/contrib/svn2host
--- a/usr/share/rear/contrib/svn2host
+++ b/usr/share/rear/contrib/svn2host
@@ -45,7 +45,12 @@ for h in "$@" ; do
 	fi
 
 	# copy dist archive to host
-	scp "$distarchive" $h:$distarchive
+	if ! err=$(scp "$distarchive" $h:$distarchive 2>&1) ; then
+		echo "ERROR Could not scp rear dist archive to '$h':"
+		echo "$err"
+		FAILED=( "${FAILED[@]}" "$h -> Could not scp dist archive: $err")
+		continue
+	fi
 
 	if ssh $h type -p rpmbuild >/dev/null ; then
 	# this is an RPM type host, build it
