Minor corrections according to https://github.com/rear/rear/pull/1530#pullrequestreview-69180844

diff --git a/usr/share/rear/skel/default/etc/scripts/run-sshd b/usr/share/rear/skel/default/etc/scripts/run-sshd
--- a/usr/share/rear/skel/default/etc/scripts/run-sshd
+++ b/usr/share/rear/skel/default/etc/scripts/run-sshd
@@ -1,10 +1,10 @@
 #!/bin/bash
 # check inittab for "ssh:23:respawn:/bin/sshd -D"
-if $(grep -q ^ssh: /etc/inittab) ; then
-    if ! ls /etc/ssh/*key* &>/dev/null ; then
-        # generate at least one SSH host key if there is none because
-        # a running sshd without any SSH host key is not accessible from remote
-        # (on the remote host one gets "Connection to recovery.system.IP.address closed.")
+if grep -q '^ssh:' /etc/inittab ; then
+    if ! test -s /etc/ssh/ssh_host_rsa_key ; then
+        # generate at least an rsa SSH host key if there is none to be fail-safe against
+        # running sshd possibly without any SSH host key which is not accessible from remote
+        # (on the remote host one would get "Connection to recovery.system.IP.address closed.")
         # cf. build/default/500_ssh_setup.sh
         ssh-keygen -q -t rsa -N '' -f /etc/ssh/ssh_host_rsa_key
     fi
