Update system-setup
Do no longer call
eval echo "... $command ..."
but instead call plain
echo "... $command ..."
(default command='rear $rear_options recover')
to keep the code simple and fail-safe because
"Better very simple code than oversophisticated (possibly fragile) constructs.", cf.
https://github.com/rear/rear/wiki/Coding-Style

diff --git a/usr/share/rear/skel/default/etc/scripts/system-setup b/usr/share/rear/skel/default/etc/scripts/system-setup
--- a/usr/share/rear/skel/default/etc/scripts/system-setup
+++ b/usr/share/rear/skel/default/etc/scripts/system-setup
@@ -196,18 +196,18 @@ if automatic_recovery ; then
     choices=( "View Relax-and-Recover log file(s)"
               "Login at the rescue system"
             )
-    eval echo "Launching \'$RECOVERY_COMMANDS_LABEL\' automatically"
+    echo "Launching '$RECOVERY_COMMANDS_LABEL' automatically"
     for command in "${RECOVERY_COMMANDS[@]}" ; do
-        rear_debug && eval echo "Running RECOVERY_COMMANDS \'$command\'"
+        rear_debug && echo "Running RECOVERY_COMMANDS '$command'"
         eval "$command"
         recovery_command_exit_code=$?
-        test $recovery_command_exit_code -eq 0 || eval echo "\'eval $command\' results exit code $recovery_command_exit_code"
+        test $recovery_command_exit_code -eq 0 || echo "'eval $command' results exit code $recovery_command_exit_code"
     done
     if test $recovery_command_exit_code -eq 0 ; then
-        eval echo "\'$RECOVERY_COMMANDS_LABEL\' finished successfully"
+        echo "'$RECOVERY_COMMANDS_LABEL' finished successfully"
         choices+=( "$REBOOT_COMMANDS_LABEL" )
     else
-        eval echo "\'$RECOVERY_COMMANDS_LABEL\' failed with exit code $recovery_command_exit_code"
+        echo "'$RECOVERY_COMMANDS_LABEL' failed with exit code $recovery_command_exit_code"
     fi
     PS3="Select what to do "
     select choice in "${choices[@]}" ; do
@@ -249,15 +249,15 @@ if unattended_recovery ; then
     choices=( "View Relax-and-Recover log file(s)"
               "Login at the rescue system"
             )
-    eval echo "Launching \'$RECOVERY_COMMANDS_LABEL\' automatically"
+    echo "Launching '$RECOVERY_COMMANDS_LABEL' automatically"
     for command in "${RECOVERY_COMMANDS[@]}" ; do
-        rear_debug && eval echo "Running RECOVERY_COMMANDS \'$command\'"
+        rear_debug && echo "Running RECOVERY_COMMANDS '$command'"
         eval "$command"
         recovery_command_exit_code=$?
-        test $recovery_command_exit_code -eq 0 || eval echo "\'eval $command\' results exit code $recovery_command_exit_code"
+        test $recovery_command_exit_code -eq 0 || echo "'eval $command' results exit code $recovery_command_exit_code"
     done
     if test $recovery_command_exit_code -eq 0 ; then
-        eval echo "\'$RECOVERY_COMMANDS_LABEL\' finished successfully"
+        echo "'$RECOVERY_COMMANDS_LABEL' finished successfully"
         echo "'$REBOOT_COMMANDS_LABEL' in $USER_INPUT_INTERRUPT_TIMEOUT seconds (Ctrl-C to interrupt)"
         sleep $USER_INPUT_INTERRUPT_TIMEOUT
         for command in "${REBOOT_COMMANDS[@]}" ; do
@@ -273,7 +273,7 @@ if unattended_recovery ; then
         # it proceeds after 10 seconds with the login screen:
         sleep 10
     else
-        eval echo "\'$RECOVERY_COMMANDS_LABEL\' failed with exit code $recovery_command_exit_code"
+        echo "'$RECOVERY_COMMANDS_LABEL' failed with exit code $recovery_command_exit_code"
         PS3="Select what to do "
         select choice in "${choices[@]}" ; do
             case "$REPLY" in
