New RECOVERY_COMMANDS array (#3089)
New RECOVERY_COMMANDS array (plus RECOVERY_COMMANDS_LABEL)
to specifiy the "rear recover" commands which are automatically called
after the ReaR recovery system has started up to recreate the system
in 'auto_recover'/'automatic' or 'unattended' mode.
By default "rear recover" is called (which was hardcoded before).
See https://github.com/rear/rear/pull/3070#discussion_r1397363473
Additionally in skel/default/etc/scripts/system-setup call bash 'read'
with a 'timeout' (normally 30 seconds or 3 seconds in unattended mode)
to automatically proceed (in particular in unattended mode),
cf. https://github.com/rear/rear/issues/1366

diff --git a/usr/share/rear/skel/default/etc/scripts/system-setup b/usr/share/rear/skel/default/etc/scripts/system-setup
--- a/usr/share/rear/skel/default/etc/scripts/system-setup
+++ b/usr/share/rear/skel/default/etc/scripts/system-setup
@@ -1,8 +1,8 @@
 #!/bin/bash
 
 # system-setup has been split into scripts under /etc/scripts/system-setup.d
-# the purpose is to have different skel areas contribute different scripts into
-# the system-setup stage
+# the purpose is to have different skel areas contribute different scripts
+# into the system-setup stage
 
 # Set null globbing, we need this for our scripts (cf. usr/sbin/rear).
 # With nullglob set when e.g. for foo*bar no file matches are found, then foo*bar is removed
@@ -50,24 +50,6 @@ function automatic_recovery() {
 # cf. the 'if rear_debug' part below:
 sleep 1
 
-if rear_debug ; then
-    echo -e "\nIn Relax-and-Recover debug mode a shell will be started by default on tty9\n"
-    read -n 1 -p "Press ENTER or type a digit '2...8' for another tty or '0' to skip it "
-    case "$REPLY" in
-        (0)
-            echo -e "\nNo debug mode shell started\n"
-            ;;
-        ([2-8])
-            /bin/bash </dev/tty$REPLY >/dev/tty$REPLY 2>&1 &
-            echo -e "\nStarted debug mode shell on tty$REPLY\n"
-            ;;
-        (*)
-            /bin/bash </dev/tty9 >/dev/tty9 2>&1 &
-            echo -e "\nStarted debug mode shell on tty9\n"
-            ;;
-    esac
-fi
-
 # Because "rear recover" won't work without default.conf
 # we abort when there is no default.conf (or when it is empty),
 # cf. https://github.com/rear/rear/pull/3070#discussion_r1389361339
@@ -92,15 +74,37 @@ fi
 SECRET_OUTPUT_DEV="null"
 # Sourcing of the conf/default.conf file as we may use some defined variables or arrays
 # E.g. UDEV_NET_MAC_RULE_FILES is used by script 55-migrate-network-devices.sh
-source /usr/share/rear/conf/default.conf || echo -e "\n'source /usr/share/rear/conf/default.conf' failed with exit code $?\n"
+source /usr/share/rear/conf/default.conf || echo -e "\n'source /usr/share/rear/conf/default.conf' failed with exit code $?"
 # Sourcing user and rescue configuration as we need some variables
 # (EXCLUDE_MD5SUM_VERIFICATION right now and other variables in the system setup scripts):
 # The order of sourcing should be 'site' then 'local' and as last 'rescue'
 for conf in site local rescue ; do
     if test -s /etc/rear/$conf.conf ; then
-        source /etc/rear/$conf.conf || echo -e "\n'source /etc/rear/$conf.conf' failed with exit code $?\n"
+        source /etc/rear/$conf.conf || echo -e "\n'source /etc/rear/$conf.conf' failed with exit code $?"
     fi
 done
+
+# Default USER_INPUT_INTERRUPT_TIMEOUT is 30 seconds and default USER_INPUT_UNATTENDED_TIMEOUT is 3 seconds:
+unattended_recovery && timeout=$USER_INPUT_UNATTENDED_TIMEOUT || timeout=$USER_INPUT_INTERRUPT_TIMEOUT
+if rear_debug ; then
+    # Messages should not be longer than 80 characters
+    # because this is the usual maximum usable width here:
+    echo -e "\nIn Relax-and-Recover debug mode a shell will be started by default on tty9"
+    read -n 1 -t $timeout -p "Press ENTER or type a tty digit '2...9' or '0' to skip (timeout $timeout) "
+    case "$REPLY" in
+        (0)
+            echo -e "\nNo debug mode shell started"
+            ;;
+        ([2-9])
+            /bin/bash </dev/tty$REPLY >/dev/tty$REPLY 2>&1 &
+            echo -e "\nStarted debug mode shell on tty$REPLY"
+            ;;
+        (*)
+            /bin/bash </dev/tty9 >/dev/tty9 2>&1 &
+            echo -e "\nStarted debug mode shell by default on tty9"
+            ;;
+    esac
+fi
 
 # Verifying md5sums must happen first of all during recovery system startup
 # before files may get changed by the recovery system startup scripts below
@@ -113,7 +117,7 @@ done
 # The /md5sums.txt file would be empty if the md5sums were not successfully created
 # during "rear mkrescue/mkbackup" by the build/default/995_md5sums_rootfs.sh script:
 if test -s "/md5sums.txt" ; then
-    echo -e "\nVerifying md5sums of the files in the Relax-and-Recover rescue system\n"
+    echo -e "\nVerifying md5sums of the files in the Relax-and-Recover rescue system"
     # /etc/motd is excluded because it was changed above when default.conf is missing.
     # /etc/issue is excluded to avoid that verifying its md5sum fails with "./etc/issue: FAILED"
     # when there is no rsa SSH host key /etc/ssh/ssh_host_rsa_key in the recovery system
@@ -129,13 +133,13 @@ if test -s "/md5sums.txt" ; then
     test "$EXCLUDE_MD5SUM_VERIFICATION" && egrep_pattern+="|$EXCLUDE_MD5SUM_VERIFICATION"
     # Regardless of '--quiet' md5sum shows "FAILED" messages nevertheless (cf. 'man md5sum'):
     if grep -E -v "$egrep_pattern" md5sums.txt | md5sum --quiet --check ; then
-        echo -e "md5sums are OK\n"
+        echo "md5sums are OK"
     else
         # In case of a FAILED md5sum inform the user:
         echo "Possibly corrupted Relax-and-Recover rescue system"
         if rear_debug ; then
             # In debug mode let the user confirm to proceed:
-            read -p "Press ENTER to proceed 'bona fide' nevertheless "
+            read -t $timeout -p "Press ENTER to proceed 'bona fide' nevertheless (timeout $timeout) "
         else
             # In non-debug mode wait USER_INPUT_INTERRUPT_TIMEOUT (by default 30 seconds)
             # so that the user can read and understand the md5sum output (could be several lines)
@@ -149,7 +153,8 @@ fi
 echo -e "\nConfiguring Relax-and-Recover rescue system\n"
 for system_setup_script in /etc/scripts/system-setup.d/*.sh ; do
     if rear_debug ; then
-        read -p "Press ENTER to run $( basename $system_setup_script ) "
+        read -t $timeout -p "Press ENTER to run $( basename $system_setup_script ) (timeout $timeout) "
+        echo
         set -x
         source $system_setup_script || echo -e "\n'source $system_setup_script' results exit code $?\n"
         # The only known way how to do 'set +x' after 'set -x' without a '+ set +x' output:
@@ -175,26 +180,34 @@ echo -e "\nRelax-and-Recover rescue system is ready\n"
 # unless in unattended_recovery mode where there is normally no watching user:
 unattended_recovery || sleep $USER_INPUT_UNATTENDED_TIMEOUT
 
-# In debug mode run the automated 'rear recover' also with debug options.
+# Make it explicit that the 'recover' workflow is always verbose (cf. usr/sbin/rear)
+# so when a 'rear $rear_options recover' command is shown to the user it contains '-v':
+rear_options='-v'
+# In debug mode run an automated 'rear $rear_options recover' command in debugscript mode.
 # Because the kernel command line option 'debug' means 'set -x' for the system setup scripts
-# it also means '-D' (i.e. 'set -x') for the automated 'rear recover' run:
-if rear_debug ; then
-    rear_debug_options='-D'
-else
-    rear_debug_options=''
-fi
+# it should also mean '-D' (i.e. 'set -x') for an automated 'rear $rear_options recover' run:
+rear_debug && rear_options='-D'
+# In unattended_recovery mode run an automated 'rear $rear_options recover' in non-interactive mode:
+unattended_recovery && rear_options+=' --non-interactive'
 
-# Launch "rear recover" automatically:
+# In automatic_recovery mode call RECOVERY_COMMANDS automatically
+# but without automated calling REBOOT_COMMANDS after successful recovery:
 if automatic_recovery ; then
     choices=( "View Relax-and-Recover log file(s)"
-              "Go to Relax-and-Recover shell"
+              "Login at the rescue system"
             )
-    echo -e "\nLaunching 'rear recover' automatically\n"
-    if rear $rear_debug_options recover ; then
-        echo -e "\n'rear recover' finished successfully\n"
+    echo "Launching '$RECOVERY_COMMANDS_LABEL' automatically"
+    for command in "${RECOVERY_COMMANDS[@]}" ; do
+        rear_debug && echo "Running RECOVERY_COMMANDS '$command'"
+        eval "$command"
+        recovery_command_exit_code=$?
+        test $recovery_command_exit_code -eq 0 || echo "'eval $command' results exit code $recovery_command_exit_code"
+    done
+    if test $recovery_command_exit_code -eq 0 ; then
+        echo "'$RECOVERY_COMMANDS_LABEL' finished successfully"
         choices+=( "$REBOOT_COMMANDS_LABEL" )
     else
-        echo -e "\n'rear recover' failed, check the Relax-and-Recover log file(s)\n"
+        echo "'$RECOVERY_COMMANDS_LABEL' failed with exit code $recovery_command_exit_code"
     fi
     PS3="Select what to do "
     select choice in "${choices[@]}" ; do
@@ -211,9 +224,17 @@ if automatic_recovery ; then
                 ;;
             (3)
                 for command in "${REBOOT_COMMANDS[@]}" ; do
-                    echo "Running REBOOT_COMMANDS '$command'"
-                    eval "$command" || echo -e "\n'eval $command' results exit code $?\n"
+                    rear_debug && echo "Running REBOOT_COMMANDS '$command'"
+                    eval "$command" || echo "'eval $command' results exit code $?"
                 done
+                # Wait hardcoded 10 seconds to not let this script "just proceed"
+                # because it would proceed with an iteration of the 'select' loop
+                # which is not wanted for the normal reboot/poweroff cases
+                # so we sleep 10 seconds to give reboot/poweroff some time
+                # to terminate this script while it is idle waiting here
+                # but in exceptional cases (when REBOOT_COMMANDS did not reboot/poweroff)
+                # it proceeds after 10 seconds with an iteration of the 'select' loop:
+                sleep 10
                 ;;
         esac
         for (( i=1 ; i <= ${#choices[@]} ; i++ )) ; do
@@ -222,23 +243,37 @@ if automatic_recovery ; then
     done 2>&1
 fi
 
-# In unattended mode launch "rear --non-interactive recover" automatically 
-# i.e. with automated "reboot" (reboot_command) after successful recovery:
+# In unattended_recovery mode call RECOVERY_COMMANDS automatically
+# plus automated calling REBOOT_COMMANDS after successful recovery:
 if unattended_recovery ; then
     choices=( "View Relax-and-Recover log file(s)"
-              "Go to Relax-and-Recover shell"
+              "Login at the rescue system"
             )
-    echo -e "\nLaunching 'rear recover' automatically in unattended (non-interactive) mode\n"
-    if rear $rear_debug_options --non-interactive recover ; then
-        echo -e "\n'rear recover' finished successfully\n"
-        echo -e "\n'$REBOOT_COMMANDS_LABEL' in $USER_INPUT_INTERRUPT_TIMEOUT seconds (Ctrl-C to interrupt)\n"
+    echo "Launching '$RECOVERY_COMMANDS_LABEL' automatically"
+    for command in "${RECOVERY_COMMANDS[@]}" ; do
+        rear_debug && echo "Running RECOVERY_COMMANDS '$command'"
+        eval "$command"
+        recovery_command_exit_code=$?
+        test $recovery_command_exit_code -eq 0 || echo "'eval $command' results exit code $recovery_command_exit_code"
+    done
+    if test $recovery_command_exit_code -eq 0 ; then
+        echo "'$RECOVERY_COMMANDS_LABEL' finished successfully"
+        echo "'$REBOOT_COMMANDS_LABEL' in $USER_INPUT_INTERRUPT_TIMEOUT seconds (Ctrl-C to interrupt)"
         sleep $USER_INPUT_INTERRUPT_TIMEOUT
         for command in "${REBOOT_COMMANDS[@]}" ; do
-            echo "Running REBOOT_COMMANDS '$command'"
-            eval "$command" || echo -e "\n'eval $command' results exit code $?\n"
+            rear_debug && echo "Running REBOOT_COMMANDS '$command'"
+            eval "$command" || echo "'eval $command' results exit code $?"
         done
+        # Wait hardcoded 10 seconds to not let this script "just proceed"
+        # because it would show the login screen when this script finished
+        # which is not wanted for the normal reboot/poweroff cases
+        # so we sleep 10 seconds to give reboot/poweroff some time
+        # to terminate this script while it is idle waiting here
+        # but in exceptional cases (when REBOOT_COMMANDS did not reboot/poweroff)
+        # it proceeds after 10 seconds with the login screen:
+        sleep 10
     else
-        echo -e "\n'rear recover' failed, check the Relax-and-Recover log file(s)\n"
+        echo "'$RECOVERY_COMMANDS_LABEL' failed with exit code $recovery_command_exit_code"
         PS3="Select what to do "
         select choice in "${choices[@]}" ; do
             case "$REPLY" in
