New RECOVERY_COMMANDS array
In skel/default/etc/scripts/system-setup
added RECOVERY_COMMANDS
(plus RECOVERY_COMMANDS_LABEL)

diff --git a/usr/share/rear/skel/default/etc/scripts/system-setup b/usr/share/rear/skel/default/etc/scripts/system-setup
--- a/usr/share/rear/skel/default/etc/scripts/system-setup
+++ b/usr/share/rear/skel/default/etc/scripts/system-setup
@@ -189,12 +189,18 @@ if automatic_recovery ; then
     choices=( "View Relax-and-Recover log file(s)"
               "Go to Relax-and-Recover shell"
             )
-    echo -e "\nLaunching 'rear recover' automatically\n"
-    if rear $rear_debug_options recover ; then
-        echo -e "\n'rear recover' finished successfully\n"
+    echo -e "\nLaunching '$RECOVERY_COMMANDS_LABEL' automatically\n"
+    for command in "${RECOVERY_COMMANDS[@]}" ; do
+        echo "Running RECOVERY_COMMANDS '$command'"
+        eval "$command"
+        recovery_command_exit_code=$?
+        test $recovery_command_exit_code -eq 0 || echo -e "\n'eval $command' results exit code $recovery_command_exit_code\n"
+    done
+    if test $recovery_command_exit_code -eq 0 ; then
+        echo -e "\n'$RECOVERY_COMMANDS_LABEL' finished successfully\n"
         choices+=( "$REBOOT_COMMANDS_LABEL" )
-    else
-        echo -e "\n'rear recover' failed, check the Relax-and-Recover log file(s)\n"
+     else
+        echo -e "\n'$RECOVERY_COMMANDS_LABEL' failed with exit code $recovery_command_exit_code\n"
     fi
     PS3="Select what to do "
     select choice in "${choices[@]}" ; do
@@ -214,6 +220,15 @@ if automatic_recovery ; then
                     echo "Running REBOOT_COMMANDS '$command'"
                     eval "$command" || echo -e "\n'eval $command' results exit code $?\n"
                 done
+                # Wait hardcoded 10 seconds to not let this script "just proceed"
+                # because it would proceed with an iteration of the 'select' loop
+                # which is not wanted for the normal 'reboot' or 'poweroff' cases
+                # so we sleep 10 seconds to give 'reboot' or 'poweroff' some time
+                # (both 'umount' and 'sleep 3' before actual 'reboot' or 'poweroff')
+                # to terminate this script (without iteration of the 'select' loop)
+                # but in exceptional cases (e.g. when REBOOT_COMMANDS failed)
+                # it proceeds after 10 seconds with an iteration of the 'select' loop:
+                sleep 10
                 ;;
         esac
         for (( i=1 ; i <= ${#choices[@]} ; i++ )) ; do
