Update system-setup
Use REBOOT_COMMANDS and
abort (i.e. exit 1) when there is no default.conf and
show exit value of sourced scripts and called reboot commands.

diff --git a/usr/share/rear/skel/default/etc/scripts/system-setup b/usr/share/rear/skel/default/etc/scripts/system-setup
--- a/usr/share/rear/skel/default/etc/scripts/system-setup
+++ b/usr/share/rear/skel/default/etc/scripts/system-setup
@@ -66,20 +66,28 @@ if rear_debug ; then
     esac
 fi
 
+# Because "rear recover" won't work without default.conf
+# we abort when there is no default.conf (or when it is empty),
+# cf. https://github.com/rear/rear/pull/3070#discussion_r1389361339
+if ! test -s /usr/share/rear/conf/default.conf ; then
+    echo -e "\nERROR: ReaR recovery cannot work without /usr/share/rear/conf/default.conf - exiting\n"
+    exit 1
+fi
+
 # Set SECRET_OUTPUT_DEV because secret default values are set via
 #   { VARIABLE='secret value' ; } 2>>/dev/$SECRET_OUTPUT_DEV
 # cf. https://github.com/rear/rear/pull/3034#issuecomment-1691609782
 SECRET_OUTPUT_DEV="null"
 # Sourcing of the conf/default.conf file as we may use some defined variables or arrays
 # E.g. UDEV_NET_MAC_RULE_FILES is used by script 55-migrate-network-devices.sh
-if test -f /usr/share/rear/conf/default.conf ; then
-    source /usr/share/rear/conf/default.conf
-fi
+source /usr/share/rear/conf/default.conf || echo -e "\n'source /usr/share/rear/conf/default.conf' failed with exit code $?\n"
 # Sourcing user and rescue configuration as we need some variables
 # (EXCLUDE_MD5SUM_VERIFICATION right now and other variables in the system setup scripts):
 # The order of sourcing should be 'site' then 'local' and as last 'rescue'
 for conf in site local rescue ; do
-    test -f /etc/rear/$conf.conf && source /etc/rear/$conf.conf
+    if test -s /etc/rear/$conf.conf ; then
+        source /etc/rear/$conf.conf || echo -e "\n'source /etc/rear/$conf.conf' failed with exit code $?\n"
+    fi
 done
 
 # Verifying md5sums must happen first of all during recovery system startup
@@ -116,10 +124,11 @@ if test -s "/md5sums.txt" ; then
             # In debug mode let the user confirm to proceed:
             read -p "Press ENTER to proceed 'bona fide' nevertheless "
         else
-            # In non-debug mode wait 10 seconds so that the user can read the md5sum output
-            # unless in unattended_recovery mode where there is no user who reads something:
+            # In non-debug mode wait USER_INPUT_INTERRUPT_TIMEOUT (by default 30 seconds)
+            # so that the user can read and understand the md5sum output (could be several lines)
+            # unless in unattended_recovery mode where there is normally no user who reads something:
             echo -e "Proceeding 'bona fide' nevertheless...\n"
-            unattended_recovery || sleep 10
+            unattended_recovery && sleep $USER_INPUT_UNATTENDED_TIMEOUT || sleep $USER_INPUT_INTERRUPT_TIMEOUT
         fi
     fi
 fi
@@ -129,19 +138,20 @@ for system_setup_script in /etc/scripts/system-setup.d/*.sh ; do
     if rear_debug ; then
         read -p "Press ENTER to run $( basename $system_setup_script ) "
         set -x
-        source $system_setup_script
+        source $system_setup_script || echo -e "\n'source $system_setup_script' exited with $?\n"
         # The only known way how to do 'set +x' after 'set -x' without a '+ set +x' output:
         { set +x ; } 2>/dev/null
         echo
     else
         echo "Running $( basename $system_setup_script )..."
-        source $system_setup_script
+        source $system_setup_script || echo -e "\n'source $system_setup_script' exited with $?\n"
     fi
 done
 echo -e "\nRelax-and-Recover rescue system is ready\n"
-# Wait two seconds so that the user can read the 'Relax-and-Recover rescue system is ready' message
+# Wait USER_INPUT_UNATTENDED_TIMEOUT (by default 3 seconds)
+# so that the user can read the 'Relax-and-Recover rescue system is ready' message
 # on his screen before the screen gets cleared and replaced by the login screen:
-sleep 2
+sleep $USER_INPUT_UNATTENDED_TIMEOUT
 
 # In debug mode run the automated 'rear recover' also with debug options.
 # Because the kernel command line option 'debug' means 'set -x' for the system setup scripts
@@ -152,8 +162,6 @@ else
     rear_debug_options=''
 fi
 
-reboot_command="${RECOVERY_REBOOT_COMMAND:-reboot}"
-
 # Launch "rear recover" automatically:
 if automatic_recovery ; then
     choices=( "View Relax-and-Recover log file(s)"
@@ -162,7 +170,7 @@ if automatic_recovery ; then
     echo -e "\nLaunching 'rear recover' automatically\n"
     if rear $rear_debug_options recover ; then
         echo -e "\n'rear recover' finished successfully\n"
-        choices+=( "$reboot_command" )
+        choices+=( "Reboot" )
     else
         echo -e "\n'rear recover' failed, check the Relax-and-Recover log file(s)\n"
     fi
@@ -180,7 +188,10 @@ if automatic_recovery ; then
                 break
                 ;;
             (3)
-                $reboot_command
+                for command in "${REBOOT_COMMANDS[@]}" ; do
+                    echo "Running REBOOT_COMMANDS '$command'"
+                    eval "$command" || echo -e "\n'eval $command' exited with $?\n"
+                done
                 ;;
         esac
         for (( i=1 ; i <= ${#choices[@]} ; i++ )) ; do
@@ -192,7 +203,6 @@ fi
 # In unattended mode launch "rear --non-interactive recover" automatically 
 # i.e. with automated "reboot" (reboot_command) after successful recovery:
 if unattended_recovery ; then
-    timeout="${USER_INPUT_INTERRUPT_TIMEOUT:-30}"
     choices=( "View Relax-and-Recover log file(s)"
               "Go to Relax-and-Recover shell"
             )
@@ -200,8 +210,11 @@ if unattended_recovery ; then
     if rear $rear_debug_options --non-interactive recover ; then
         echo -e "\n'rear recover' finished successfully\n"
         echo -e "\n'$reboot_command' in $timeout seconds (Ctrl-C to interrupt)\n"
-        sleep $timeout
-        $reboot_command
+        sleep $USER_INPUT_INTERRUPT_TIMEOUT
+        for command in "${REBOOT_COMMANDS[@]}" ; do
+            echo "Running REBOOT_COMMANDS '$command'"
+            eval "$command" || echo -e "\n'eval $command' exited with $?\n"
+        done
     else
         echo -e "\n'rear recover' failed, check the Relax-and-Recover log file(s)\n"
         PS3="Select what to do "
