TCG Opal support: improve PBA usability and debugging
- improve wording of messages for one or multiple Opal disks
- fix hangup after empty password entry
- add emergency shell
- capture stderr messages and display those in an emergency
- enable systemd journal
- add OPALPBA_DEBUG_PASSWORD

diff --git a/usr/share/rear/skel/default/etc/scripts/unlock-opal-disks b/usr/share/rear/skel/default/etc/scripts/unlock-opal-disks
--- a/usr/share/rear/skel/default/etc/scripts/unlock-opal-disks
+++ b/usr/share/rear/skel/default/etc/scripts/unlock-opal-disks
@@ -8,48 +8,114 @@
 # system shutdown.
 
 source /usr/share/rear/lib/opal-functions.sh
+[[ -f /.OPALPBA_SETTINGS.sh ]] && source /.OPALPBA_SETTINGS.sh
 
-kernel_cmdline="$(cat /proc/cmdline)"
-
-function opal_debug() {
-    # returns 0 if Opal debug mode is requested
-    [[ " $kernel_cmdline " == *" opal_debug "* ]]
-}
-
-function be_quiet() {
-    # returns 0 if quiet boot is requested
-    [[ " $kernel_cmdline " == *" quiet "* ]]
-}
 
 function use_plymouth() {
-    # returns 0 if plymouth is to be used
+    # returns 0 if plymouth is to be used.
     type -p plymouth &>/dev/null && plymouth --ping
 }
 
 function quit_plymouth() {
-    # quits plymouth if in use
+    # quits plymouth if in use.
     use_plymouth && plymouth quit
 }
 
-function ask_for_password() {
-    # asks for a password with prompt $1, setting the variable $password
-    if ! password="$(use_plymouth && plymouth ask-for-password --prompt="$1")"; then
-        echo ""
-        read -r -s -p "$1: " password
-        echo ""
-    fi
+function display_message() {
+    local message="${1:?}"
+
+    (use_plymouth && plymouth display-message --text="$message") || echo -e "\n$message"
 }
 
-function display_message() {
-    # displays the message $1
-    (use_plymouth && plymouth display-message --text="$1") || echo -e "\n$1"
+function ask_for_password() {
+    local prompt="${1:?}"  # a colon will be appended implicitly
+    # asks for a password, setting the variable $password.
+
+    while true; do
+        if ! password="$(use_plymouth && plymouth ask-for-password --prompt="$prompt")"; then
+            echo ""
+            read -r -s -p "$prompt: " password 2>&1
+            echo ""
+        fi
+
+        if [[ -n "$password" ]]; then
+            [[ "$password" == "$OPALPBA_DEBUG_PASSWORD" ]] && exit
+            break
+        else
+            display_message "Please enter a non-empty password."
+        fi
+    done
+}
+
+error_log="/error-log.$$"
+exec 2> "$error_log"
+
+function emergency_response() {
+    # drop into an emergency shell if this script terminates unexpectedly.
+
+    exec 2>&1
+
+    display_message "Entering emergency shell..."
+    sleep 3
+    quit_plymouth
+
+    local history_file="/.bash_history.$$" rc_file="/.bashrc.$$"
+
+    cat > "$history_file" << '--EOF--'
+sedutil-cli --help |& less  # help on low-level administration of Opal-compliant disks
+sedutil-cli --scan  # scan for Opal-compliant disks
+sedutil-cli --query /dev/sda
+journalctl  # show system startup log
+exit
+--EOF--
+
+    cat > "$rc_file" << '--EOF--'
+export PS1="OPAL PBA> "
+rear() {
+    echo "ERROR: You cannot run rear from within the OPAL PBA." >&2
+    return 1
+}
+cd /
+--EOF--
+
+    cat > /etc/motd << '--EOF--'
+
+This is the OPAL PBA emergency shell.
+
+See history for useful commands. Exit the shell to shut down the system.
+
+--EOF--
+
+    if [[ -s "$error_log" ]]; then
+        {
+            echo "The following errors occured when executing $0:"
+            cat "$error_log"
+            echo ""
+        } >> /etc/motd
+    fi
+
+    HISTFILE="$history_file" bash --rcfile "$rc_file"
+
+    display_message "Shutting down..."
+    sleep 3
+    shutdown now
+}
+
+trap emergency_response EXIT
+use_plymouth && plymouth update-root-fs --read-write
+
+function stop_error_handling() {
+    trap - EXIT
 }
 
 function instant_reboot() {
     quit_plymouth
+    stop_error_handling
+
     # Force immediate hardware reboot via Magic SysRq key
     echo 1 > /proc/sys/kernel/sysrq
     echo b > /proc/sysrq-trigger
+
     # Fallback if the previous method did not work
     sleep 1
     reboot --force
@@ -57,9 +123,12 @@ function instant_reboot() {
 
 function instant_poweroff() {
     quit_plymouth
+    stop_error_handling
+
     # Force immediate hardware poweroff via Magic SysRq key
     echo 1 > /proc/sys/kernel/sysrq
     echo o > /proc/sysrq-trigger
+
     # Fallback if the previous method did not work
     sleep 1
     poweroff --force
@@ -77,16 +146,10 @@ done
 devices=( $(opal_devices) )
 declare -i device_count=${#devices[@]}
 if (( device_count == 0 )); then
-    if opal_debug; then
-        display_message "Could not detect TCG Opal-compliant disks. Entering shell..."
-        sleep 3
-        quit_plymouth
-        bash --login
-    else
-        display_message "Could not detect TCG Opal-compliant disks. Powering off..."
-        sleep 3
-        instant_poweroff
-    fi
+    display_message "Could not detect TCG Opal-compliant disks."
+    echo "Could not detect TCG Opal-compliant disks." >&2
+    sleep 3
+    exit
 fi
 
 # Query TCG Opal-compliant disks to determine the maximum number of authentication attempts
@@ -100,34 +163,42 @@ for device in "${devices[@]}"; do
 done
 
 # Ask for a password, unlock TCG Opal-compliant disks, reboot if successful
+if (( device_count == 1 )); then
+    password_prompt="Enter password to unlock disk"
+    unsuccessful_unlock_response="Could not unlock the disk."
+else
+    password_prompt="Enter password to unlock disks"
+    unsuccessful_unlock_response="Could not unlock any of $device_count disks."
+fi
+
 declare -i attempt=0
 while (( attempt < max_authentications )); do
     attempt+=1
 
-    ask_for_password "Enter password to unlock disks"
+    ask_for_password "$password_prompt"
 
     # Success in this case is achieved if at least one device can be unlocked.
     # If other devices require different passwords for unlocking, we assume
     # that this is intentional and will be dealt with by other means.
     declare -i unlocked_device_count=0
     for device in "${devices[@]}"; do
-        opal_device_unlock "$device" "$password" &>/dev/null && unlocked_device_count+=1
+        opal_device_unlock "$device" "$password" >/dev/null && unlocked_device_count+=1
     done
 
     if (( unlocked_device_count > 0 )); then
-        display_message "$unlocked_device_count disk(s) unlocked, rebooting..."
-        sleep 1
-        instant_reboot
-    elif (( device_count == 0 )); then
-        display_message "No disks to unlock, rebooting..."
+        if (( device_count == 1 && unlocked_device_count == 1 )); then
+            display_message "Disk unlocked, rebooting..."
+        else
+            display_message "$unlocked_device_count of $device_count disks unlocked, rebooting..."
+        fi
         sleep 1
         instant_reboot
     else
-        display_message "Could not unlock any disk."
+        display_message "$unsuccessful_unlock_response"
     fi
 done
 
-# If unsuccessful, power off.
+# If finally unsuccessful, power off.
 # This is required as TCG Opal-compliant disks will refuse further authentication attempts before being reset.
 display_message "Powering off after $attempt unsuccessful attempts..."
 sleep 3
