TCG Opal support: consistently refer to Opal 2, harmonize wording

diff --git a/usr/share/rear/skel/default/etc/scripts/unlock-opal-disks b/usr/share/rear/skel/default/etc/scripts/unlock-opal-disks
--- a/usr/share/rear/skel/default/etc/scripts/unlock-opal-disks
+++ b/usr/share/rear/skel/default/etc/scripts/unlock-opal-disks
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Unlock TCG Opal-compliant disks and reboot to continue booting the 'real' operating system
+# Unlock TCG Opal 2-compliant disks and reboot to continue booting the 'real' operating system
 #
 # This script executes the final stage of a TCG Opal pre-boot authentication (PBA) boot.
 # It is expected that this script executes on a volatile system running entirely on RAM file systems.
@@ -150,13 +150,13 @@ done
 devices=( $(opal_devices) )
 declare -i device_count=${#devices[@]}
 if (( device_count == 0 )); then
-    display_message "Could not detect TCG Opal-compliant disks."
-    echo "Could not detect TCG Opal-compliant disks." >&2
+    display_message "Could not detect TCG Opal 2-compliant disks."
+    echo "Could not detect TCG Opal 2-compliant disks." >&2
     sleep 3
     exit
 fi
 
-# Query TCG Opal-compliant disks to determine the maximum number of authentication attempts
+# Query TCG Opal 2-compliant disks to determine the maximum number of authentication attempts
 declare -i max_authentications=5  # self-imposed limit to begin with
 for device in "${devices[@]}"; do
     device_max_authentications="$(opal_device_max_authentications "$device")"
@@ -166,7 +166,7 @@ for device in "${devices[@]}"; do
     fi
 done
 
-# Ask for a password, unlock TCG Opal-compliant disks, reboot if successful
+# Ask for a password, unlock TCG Opal 2-compliant disks, reboot if successful
 if (( device_count == 1 )); then
     password_prompt="Enter password to unlock disk"
     unsuccessful_unlock_response="Could not unlock the disk."
@@ -203,7 +203,7 @@ while (( attempt < max_authentications )); do
 done
 
 # If finally unsuccessful, power off.
-# This is required as TCG Opal-compliant disks will refuse further authentication attempts before being reset.
+# This is required as TCG Opal 2-compliant disks will refuse further authentication attempts before being reset.
 display_message "Powering off after $attempt unsuccessful attempts..."
 sleep 3
 instant_poweroff
