Update sbin/rear

diff --git a/usr/sbin/rear b/usr/sbin/rear
--- a/usr/sbin/rear
+++ b/usr/sbin/rear
@@ -75,63 +75,24 @@ readonly INITIAL_BASH_FLAGS_AND_OPTIONS_COMMANDS="$( get_bash_flags_and_options_
 # and https://github.com/rear/rear/issues/3259#issuecomment-2385745545
 # and https://github.com/rear/rear/issues/3319#issuecomment-2360546784
 # and https://github.com/rear/rear/issues/3319#issuecomment-2363556217
-# For sourcing via 'source' later (see below) trusted sourcing gets set up
-# by replacing this 'source' forbid function by a 'source' wrapper function
-# in lib/_framework-setup-and-functions.sh which implements trusted sourcing
-# which is then the only allowed way to normally source a file in ReaR.
-# For exceptional cases 'builtin source' can still be used to source files
-# that are known to be trusted (e.g. with hardcoded trusted path).
-# The point is that we can reliably find all code places where 'builtin' is used
-# so we can reliably check such exceptional cases at any time to keep ReaR secure
-# (in particular we can also find where the undesirable form 'builtin .' is used):
 function source () {
     echo -e "ERROR: BUG in $PRODUCT\nForbidden usage of 'source' in\n  source $*\nPlease report it at $BUG_REPORT_SITE" >&2
     exit 1
 }
-# To be on the safe side sourcing via '.' is forbidden in general in ReaR because
-# it is basically impossible to reliably find all code places where '.' is used for sourcing
-# see https://github.com/rear/rear/issues/3260#issuecomment-2248252572
-# except explicitly specified files by TRUSTED_SOURCING_VIA_DOT+=( /path/to/actual_file )
-# where /path/to/actual_file is the actual file with leading / and symlinks resolved
-# i.e. /path/to/actual_file is what 'readlink -e path/to/file' returns when '. path/to/file' is called
-# plus /path/to/actual_file must be located below one of the TRUSTED_PATHS
-# and the owner of /path/to/actual_file must be one of the TRUSTED_OWNERS
-# because this '.' wrapper function calls 'source' which is the 'source' wrapper function:
-TRUSTED_SOURCING_VIA_DOT=()
 function . () {
-    local file="$1"
-    local actual_path=""
-    local trusted_path=""
-    # Empty TRUSTED_SOURCING_VIA_DOT means sourcing via '.' is forbidden:
-    if test ${#TRUSTED_SOURCING_VIA_DOT[@]} -eq 0 ; then
-        echo -e "ERROR: Forbidden usage of '.' instead of 'source' in\n  . $*\nTRUSTED_SOURCING_VIA_DOT is empty" >&2
-        exit 1
-    fi
-    # It is not trusted when it is neither a regular file nor a link to a regular file:
-    if ! test -f "$file" ; then
-        echo -e "ERROR: Forbidden usage of '.' in\n  . $*\n'$file' is neither a regular file nor a link to a regular file" >&2
-        exit 1
-    fi
-    # Get the full path of the actual file (i.e. with leading / and symlinks resolved)
-    # e.g. /etc/os-release is a symbolic link to /usr/lib/os-release (at least on openSUSE Leap 15.6).
-    # It cannot be trusted when readlink fails:
-    if ! actual_path="$( readlink -e "$file" )" ; then
-        echo -e "ERROR: Forbidden usage of '.' in\n  . $*\n'$file' cannot be trusted because 'readlink -e $file' failed" >&2
-        exit 1
-    fi
-    # Check if it can be trusted because TRUSTED_SOURCING_VIA_DOT contains the actual file path:
-    for trusted_path in "${TRUSTED_SOURCING_VIA_DOT[@]}" ; do
-        test "$actual_path" = "$trusted_path" && break
-    done
-    # When after the 'for' loop "$actual_path" = "$trusted_path" then the actual file path is in TRUSTED_SOURCING_VIA_DOT:
-    if ! test "$actual_path" = "$trusted_path" ; then
-        echo -e "ERROR: Forbidden usage of '.' in\n  . $*\nbecause actual path '$actual_path' not in TRUSTED_SOURCING_VIA_DOT" >&2
-        exit 1
-    fi
-    # The actual work (source the file):
-    source "$@"
-    # The return code of this '.' wrapper function is the return code of the 'source' wrapper function.
+    echo -e "ERROR: BUG in $PRODUCT\nForbidden usage of '.' in\n  . $*\nPlease report it at $BUG_REPORT_SITE" >&2
+    exit 1
 }
+# Later when _framework-setup-and-functions.sh gets sourced
+# those two 'source' and '.' forbid functions are replaced
+# by two 'source' and '.' wrapper functions in _framework-setup-and-functions.sh
+# where the 'source' wrapper function enforces trusted sourcing and
+# the '.' wrapper function enforces trusted sourcing via '.' for exceptional cases.
+# For special cases 'builtin source' can still be used to source files
+# that are known to be trusted (e.g. with hardcoded trusted path).
+# The point is that we can reliably find all code places where 'builtin' is used
+# so we can reliably check such special cases at any time to keep ReaR secure
+# (in particular we can also find where the undesirable form 'builtin .' is used):
 
 # Set machine readable and human readable start date and time values.
 # START_SECONDS is set to have a single fixed point in time
@@ -599,7 +560,6 @@ if ! builtin source $SHARE_DIR/lib/_framework-setup-and-functions.sh ; then
     echo -e "ERROR: BUG in $PRODUCT\nFailed to source $SHARE_DIR/lib/_framework-setup-and-functions.sh\nPlease report it at $BUG_REPORT_SITE" >&2
     exit 1
 fi
-
 # Via source usr/share/rear/lib/_framework-setup-and-functions.sh
 # those final exit tasks are now set to be executed (via bash EXIT trap) in the following order:
 # "(( EXIT_FAIL_MESSAGE )) && echo '${MESSAGE_PREFIX}$PROGRAM $WORKFLOW failed, check $RUNTIME_LOGFILE for details' 1>&8"
@@ -612,8 +572,8 @@ fi
 # see https://github.com/rear/rear/issues/3259#issuecomment-2385745545
 # Additionally TRUSTED_OWNERS and TRUSTED_PATHS are set to default values
 # but TRUSTED_OWNERS and TRUSTED_PATHS are not yet set 'readonly' because this is done
-# after the normal user configuration files (site.conf local.conf rescue.conf) were sourced
-# so that the user can specify what he needs, e.g. for whatever third-party (backup) software
+# after the configuration files were sourced so that the user can specify what he needs,
+# e.g. for whatever third-party (backup) software
 # see https://github.com/rear/rear/pull/3379#issuecomment-2621021213
 
 # Set RECOVERY_MODE when we are running inside a rescue/recovery system
@@ -893,15 +853,15 @@ if test "$CONFIG_APPEND_FILES" ; then
         fi
     done
 fi
-# After the user configuration files were sourced set TRUSTED_OWNERS and TRUSTED_PATHS 'readonly':
-readonly TRUSTED_OWNERS TRUSTED_PATHS
+if [ "$saved_tmpdir" != "$TMPDIR" ] ; then
+    Error "Setting TMPDIR in a configuration file is not supported. To specify a working area directory prefix, export TMPDIR before executing '$PROGRAM'"
+fi
+# After the user configuration files were sourced set TRUSTED_OWNERS and TRUSTED_PATHS and TRUSTED_SOURCING_VIA_DOT 'readonly':
+readonly TRUSTED_OWNERS TRUSTED_PATHS TRUSTED_SOURCING_VIA_DOT
 # Show the final TRUSTED_OWNERS and TRUSTED_PATHS to the user in debug mode
 # to help him if he cannot source additional configuration files in non-default paths:
 DebugPrint "Sourced files must be owned by one of the TRUSTED_OWNERS: ${TRUSTED_OWNERS[*]:-all owners are trusted}"
 DebugPrint "Sourced files must be below one of the TRUSTED_PATHS: ${TRUSTED_PATHS[*]:-all paths are trusted}"
-if [ "$saved_tmpdir" != "$TMPDIR" ] ; then
-    Error "Setting TMPDIR in a configuration file is not supported. To specify a working area directory prefix, export TMPDIR before executing '$PROGRAM'"
-fi
 
 # Nothing else should be able to add more configuration files:
 readonly CONFIG_APPEND_FILES_PATHS
