copy as user

diff --git a/tools/run-in-docker b/tools/run-in-docker
--- a/tools/run-in-docker
+++ b/tools/run-in-docker
@@ -180,7 +180,7 @@ case "${command_args[0]}" in
             if test "$(ls -l "$rear_toplevel_dir/dist" 2>/dev/null || :)" ; then
                 echo "********** Copying dist to ${dist_dest}"
                 mkdir -p "$rear_toplevel_dir/$dist_dest" || die "Could not mkdir $rear_toplevel_dir/$dist_dest"
-                cp -axT "$rear_toplevel_dir/dist/" "$rear_toplevel_dir/$dist_dest/" || die "Could not copy dist to $dist_dest"
+                cp -rxT "$rear_toplevel_dir/dist/" "$rear_toplevel_dir/$dist_dest/" || die "Could not copy dist to $dist_dest"
             fi
         done
     ;;
