error handling, disable unsuable UBI

diff --git a/tools/run-in-docker b/tools/run-in-docker
--- a/tools/run-in-docker
+++ b/tools/run-in-docker
@@ -15,8 +15,8 @@ declare -r IMAGES=(
     centos:{6,7,8} # discontinued
     sl:7           # discontinued
     quay.io/centos/centos:stream{8,9}
-    registry.access.redhat.com/ubi{7,8,9}
-    fedora:{29,30,31,32,33,34,35,36,37,38,rawhide}
+    # registry.access.redhat.com/ubi{7,8,9} basic packages like parted are missing
+    fedora:{29,31,34,37,38,rawhide}
     archlinux
     manjarolinux/base
 )
@@ -43,6 +43,11 @@ function die {
     echo -e "ERROR: $*" 1>&2
     exit 1
 }
+
+function exit_handler {
+    echo "** SCRIPT RUN TIME $SECONDS SECONDS **"
+}
+trap exit_handler EXIT
 
 extra_docker_args=()
 use_images=()
@@ -95,7 +100,7 @@ RUN git config --global --add safe.directory /rear
         printf "********** PATCHING %-40s **********\n" "$image" 1>&2
         read oldsize junk < <(docker images --format '{{.VirtualSize}}' "$image")
         docker buildx build -t "$image" \
-            --quiet "${extra_docker_args[@]}" \
+            "${extra_docker_args[@]}" \
             - <<<"$DOCKERFILE" || die "Failed building $image"
         read newsize junk < <(docker images --format '{{.VirtualSize}}' "$image")
         test "$oldsize" != "$newsize" && printf "********** %-35s %7s -> %-7s *****\n" "$image" "$oldsize" "$newsize" 
@@ -159,7 +164,11 @@ case "${command_args[0]}" in
         for image in "${use_images[@]}"; do
             printf "********** %-40s **********\n" "$image" 1>&2
             dist_dest="dist-all/${image//:/-}"
-            rm -Rf "$rear_toplevel_dir"/{build,dist,etc/rear/os.conf,var/log/rear} "$rear_toplevel_dir/${dist_dest:?}"
+            # BUG: Docker runs as root, creating build and dist as root, too
+            # SOLUTION: ?
+            rm -Rf "$rear_toplevel_dir"/{build,dist,etc/rear/os.conf,var/log/rear} "$rear_toplevel_dir/${dist_dest:?}" 2>/dev/null ||\
+                sudo rm -Rf "$rear_toplevel_dir"/{build,dist,etc/rear/os.conf,var/log/rear} "$rear_toplevel_dir/${dist_dest:?}" ||\
+                    die "Cannot clean up ReaR directory"
             docker run \
                 --rm -i \
                 --sig-proxy=false \
@@ -167,12 +176,14 @@ case "${command_args[0]}" in
                 -w /rear \
                 "${extra_docker_args[@]}" \
                 "$image" \
-                /bin/bash <<<"${command_args[@]}"
+                /bin/bash <<<"${command_args[@]}" || die "############### DOCKER RUN FAILED FOR $image"
             if test "$(ls -l "$rear_toplevel_dir/dist" 2>/dev/null || :)" ; then
                 echo "********** Copying dist to ${dist_dest}"
-                mkdir -p "$rear_toplevel_dir/$dist_dest"
-                cp -axT "$rear_toplevel_dir/dist/" "$rear_toplevel_dir/$dist_dest/"
+                mkdir -p "$rear_toplevel_dir/$dist_dest" || die "Could not mkdir $rear_toplevel_dir/$dist_dest"
+                cp -axT "$rear_toplevel_dir/dist/" "$rear_toplevel_dir/$dist_dest/" || die "Could not copy dist to $dist_dest"
             fi
         done
     ;;
 esac
+
+
